language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++', 'gcc']
      env:
        - CXX='g++'
        - CC='gcc'

install:
  - pip install -r requirements.txt

script:
  - ./setup
  - cd build
  - make
  - cd ..
  - pycodestyle --ignore=E501 test/test.py
  - BALBOA_BUILD_DIR=$PWD/build PYTHONPATH=$PWD/balboa py.test -s -vv test/test.py
  - py.test -s -vv balboa/generate.py

notifications:
  email: false
